spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zcommerce?schema=core
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
